# Generated by Django 3.1.4 on 2021-01-01 15:04

from django.db import migrations, models
import django_minio_backend.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(storage=django_minio_backend.models.MinioBackend(bucket_name='images'), upload_to=django_minio_backend.models.iso_date_prefix)),
            ],
        ),
    ]
